In [1]:
#1.
import numpy as np
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])


In [3]:
#1.a
corrected_temperature = temperature + 2

print("Original temperatures:",temperature)
print("\nCorrected temperatures:",corrected_temperature)


Original temperatures: [25 28 31 35 38 27 33 40]

Corrected temperatures: [27 30 33 37 40 29 35 42]


In [ ]:
#1.b
fahrenheit = (9/5) * corrected_temperature + 32

print("\nTemperatures in Fahrenheit:",fahrenheit)

In [4]:
#1.c
greater_than_32 = corrected_temperature[corrected_temperature > 32]

print("\nReadings greater than 32°C:",greater_than_32)



Readings greater than 32°C: [33 37 40 35 42]


In [5]:
#1.d
count = np.sum(corrected_temperature > 32)

print("\nNumber of readings exceeding 32°C:",count)


Number of readings exceeding 32°C: 5


In [6]:
#1.e
print("\nExplanation:")
print("Vectorization performs operations on the entire NumPy array at once,")
print("without explicitly using a for loop.")
print("Boolean indexing directly selects elements satisfying a condition.")
print("This makes NumPy operations faster and more efficient for large datasets.")


Explanation:
Vectorization performs operations on the entire NumPy array at once,
without explicitly using a for loop.
Boolean indexing directly selects elements satisfying a condition.
This makes NumPy operations faster and more efficient for large datasets.


In [7]:
#2
import numpy as np
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Steps matrix:",steps)


Steps matrix: [[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]


In [16]:
#2.a
total_steps = np.sum(steps)

print("Total steps recorded:",total_steps)

Total steps recorded: 84200


In [17]:
#2.b
mean_steps = np.mean(steps)

print("Mean number of steps:",mean_steps)

Mean number of steps: 7016.666666666667


In [18]:
#2.c
maximum = np.max(steps)
minimum = np.min(steps)

print("Maximum steps:",maximum)
print("Minimum steps:",minimum)


Maximum steps: 9500
Minimum steps: 4500


In [19]:
#2.d
daily_total = np.sum(steps, axis=0)

print("Total steps for each day (axis=0):",daily_total)

Total steps for each day (axis=0): [26500 27300 30400]


In [20]:
#2.e
user_total = np.sum(steps, axis=1)

print("Total steps for each user (axis=1):",user_total)

Total steps for each user (axis=1): [18300 24500 14400 27000]


In [22]:
#2.f
max_position = np.argmax(steps)
max_position_2d = np.unravel_index(np.argmax(steps), steps.shape)

print("Maximum step value:",steps[max_position_2d])

print("User/Day position:",max_position_2d)

Maximum step value: 9500
User/Day position: (np.int64(3), np.int64(2))


In [24]:
#3
import numpy as np
#a.
original = np.array([1, 2, 3, 4, 5, 6])

print("Original array:",original)

Original array: [1 2 3 4 5 6]


In [25]:
#3.b
subset = original[1:5]

print("Subset:",subset)

Subset: [2 3 4 5]


In [26]:
#3.c
subset[0] = 999

print("After modifying subset:")

print("Original:",original)

print("Subset:",subset)


After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]


In [27]:
#3.d
copied = original[1:5].copy()

copied[0] = 500

print("After modifying copied array:")

print("Original:",original)

print("Copied:",copied)

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied: [500   3   4   5]


In [28]:
#3.e
matrix = np.arange(1, 13).reshape(3, 4)

print("3 x 4 matrix:",matrix)

3 x 4 matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
#3.f
first_row = matrix[0, :]
last_row = matrix[-1, :]
second_column = matrix[:, 1]
selected_elements = matrix[0:2, 1:3]

print("First row:",first_row)

print("Last row:",last_row)

print("Second column:",second_column)

print("Rows 1-2 and columns 2-3:",selected_elements)


First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3: [[2 3]
 [6 7]]


In [31]:
#3.g
flat_array = matrix.flatten()
ravel_array = matrix.ravel()

print("Flatten:",flat_array)

print("Ravel:",ravel_array)

Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [32]:
#3.h
ravel_array[0] = 100

print("After modifying ravel array:")
print("Ravel:",ravel_array)

print("Original matrix:",matrix)

print("Original matrix IS affected because ravel() usually returns a VIEW.")

After modifying ravel array:
Ravel: [100   2   3   4   5   6   7   8   9  10  11  12]
Original matrix: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Original matrix IS affected because ravel() usually returns a VIEW.


In [33]:
#3.i

flat_array[1] = 200

print("After modifying flatten array:")
print("Flatten:",flat_array)

print("Original matrix:",matrix)

print("Original matrix is NOT affected because flatten() returns a COPY.")

After modifying flatten array:
Flatten: [  1 200   3   4   5   6   7   8   9  10  11  12]
Original matrix: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Original matrix is NOT affected because flatten() returns a COPY.


In [34]:
#3.j
print("Matrix properties:")

print("Shape:", matrix.shape)
print("Number of dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Matrix properties:
Shape: (3, 4)
Number of dimensions: 2
Size: 12
Data type: int64


In [35]:
#4
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])

In [37]:
#4.a
print("Shape of X:",X.shape)

print("Dimensions of X:",X.ndim)

Shape of X: (4, 3)
Dimensions of X: 2


In [39]:
#4.b
X_T = X.T

print("Transpose of X (X.T):",X_T)

print("\nExplanation:")
print("Transpose changes rows into columns and columns into rows.")

Transpose of X (X.T): [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

Explanation:
Transpose changes rows into columns and columns into rows.


In [40]:
#4.c
XTX = X.T @ X

print("X.T @ X:",XTX)


X.T @ X: [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


In [41]:
#4.d
XTX_inverse = np.linalg.inv(XTX)

print("Inverse of X.T @ X:",XTX_inverse)

Inverse of X.T @ X: [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


In [42]:
#4.e
beta = np.linalg.inv(X.T @ X) @ X.T @ y

print("OLS coefficients:",beta)

OLS coefficients: [-0.15921454  0.14083853 10.06302242]


In [43]:
#4.f
print("\nf. Interpretation of coefficients:")

print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])

print("""
The coefficients represent the estimated effect of each feature
on the assistance score while keeping the other features constant.

Sleep coefficient:
A one-unit increase in sleep hours changes the predicted
assistance score by approximately the sleep coefficient.

Activity coefficient:
A one-unit increase in activity level changes the predicted
assistance score by approximately the activity coefficient.

Stress coefficient:
A one-unit increase in stress level changes the predicted
assistance score by approximately the stress coefficient.
""")


f. Interpretation of coefficients:
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587

The coefficients represent the estimated effect of each feature
on the assistance score while keeping the other features constant.

Sleep coefficient:
A one-unit increase in sleep hours changes the predicted
assistance score by approximately the sleep coefficient.

Activity coefficient:
A one-unit increase in activity level changes the predicted
assistance score by approximately the activity coefficient.

Stress coefficient:
A one-unit increase in stress level changes the predicted
assistance score by approximately the stress coefficient.



In [44]:
#4.g
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("New user:",new_user)

print("Predicted assistance score:",predicted_score)

New user: [ 5 40  7]
Predicted assistance score: 75.27862544779117
